server:
  port: 8080
  servlet:
    context-path: /profile
spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 123123Aa
    database:
      default-creation=delete